### ISSUE TITLE
CIT Resewn is not detected for 1.19.1

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#58] opened 2022-07-28 15:41 UTC
When I updated my modpack to 1.19.1, MMC-export no longer found CIT Resewn from Modrinth and included the JAR instead.

Notably the JAR has not been updated on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cit-resewn/files/3855030) or [Modrinth](https://modrinth.com/mod/cit-resewn/version/1.1.1%2B1.19) during that period, so I don't know what could be the cause.

Using v2.5.1 of MMC-export.

**Comment by RozeFound** [comment] 2022-07-28 21:51
I guess the problem is CIT Resewn doesn't count 1.19.1 as supported version, that's why mmc-export ignored it.

**Comment by RozeFound** [comment] 2022-07-28 21:54
I can change the behavior to check only for major and minor version, and ignore patch, but I don't know if there will be any negative consequences

**Comment by Madis0** [comment] 2022-07-29 03:21
I would assume that most mods don't actually mark 1.19.1 on the jar yet in Modrinth. How is this one different?

**Comment by RozeFound** [comment] 2022-07-29 03:23
> I would assume that most mods don't actually mark 1.19.1 on the jar yet in Modrinth. 

You think so?

**Comment by RozeFound** [comment] 2022-07-29 03:25
Well, it will be easier to figure out what's the problem if I can reproduce the bug. Can you send me a link to modpack you're exporting?

**Comment by Madis0** [comment] 2022-07-29 03:31
Examples of mod versions that worked but don't mark as 1.19.1:
* https://modrinth.com/mod/notenoughcrashes/version/4.1.6+1.19-fabric
* https://modrinth.com/mod/fabrishot/version/1.8.0
* https://modrinth.com/mod/yosbr/version/0.1.1

Modpack version where it worked: https://modrinth.com/modpack/fabulously-optimized/version/4.0.0-beta.12 (from https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3900792)
and where it didn't (I manually removed the jar and re-added CIT Resewn to manifest for now, but automatic conversion doesn't work): https://modrinth.com/modpack/fabulously-optimized/version/4.1.0-alpha.1 (from https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3904191)

**Comment by RozeFound** [comment] 2022-07-29 03:53
Well, I was right. Examples you provided was successfully found by hash but, cit-resewn wasn't, just like lambabettergrass. But lambdabettergrass have 1.19.1 in game versions, so it was added automatically, but cit-resewn won't.

**Comment by RozeFound** [comment] 2022-07-29 04:13
Must be fixed now

**Comment by Madis0** [comment] 2022-07-29 04:30
Works. I've asked the devs why the files are different.

**Comment by Madis0** [comment] 2022-07-30 15:23
Now https://modrinth.com/mod/notenoughcrashes/version/4.1.6%2B1.18.2-fabric got bundled in 1.18.2... :(

**Comment by RozeFound** [comment] 2022-07-30 22:07
Lol

**Comment by RozeFound** [comment] 2022-07-30 22:29
Must be fixed

**Closed** 2022-07-31 08:38 UTC
Labels: bug
